application:
  server:
    name: sandeepdb
    host: 127.0.0.1
    port: 27017
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG